name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with: {submodules: true}
      - uses: actions-rs/toolchain@v1
        with: {toolchain: stable, components: "clippy, rustfmt"}
      - run: cargo clippy -- -D warnings
      - run: cargo fmt --all -- --check

  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with: {submodules: true}
      - uses: actions-rs/toolchain@v1
        with: {toolchain: stable}
      - run: cargo test
      - run: |
          sudo apt-get install musl-tools
          sudo ln -s /usr/bin/g++ /usr/bin/musl-g++
          rustup target add x86_64-unknown-linux-musl
          cargo test --target x86_64-unknown-linux-musl
        if: matrix.os == 'ubuntu-latest'
